### ISSUE TITLE
Do not mask null values

### ISSUE THREAD

**Issue by mkopylec** [aafanasev/sekret#10]
I would expect the plugin not to mask values if they are `null`.
So if password is not null:
```kotlin
Credentials(login=User, password=■■■)
```
If it's null:
```kotlin
Credentials(login=User, password=null)
```

**Comment by aafanasev** [comment]
Hi, interesting idea!

I'm thinking about a case when exposing `null` can be harmful. For example `Credentials(login=User, password=■■■, encryption=null)`, saying that the credentials are not encrypted is bad I think. What do you think?

What if we will make it customizable?

```groovy
sekret {
  hideNulls = false // true, by default
}
```

**Comment by mkopylec** [comment]
`hideNulls` property will be perfect

**Comment by mkopylec** [comment]
It would also be nice to update Kotlin to the newest version.
IntelliJ IDE fails to build the project with the newest version of the kotlin plugin

**Comment by mkopylec** [comment]
```
Error:Kotlin: [Internal Error] java.lang.IllegalStateException: The provided plugin dev.afanasev.sekret.kotlin.SekretComponentRegistrar is not compatible with this version of compiler
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.registerExtensionsFromPlugins$cli(KotlinCoreEnvironment.kt:577)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$ProjectEnvironment.registerExtensionsFromPlugins(KotlinCoreEnvironment.kt:135)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:175)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:115)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(KotlinCoreEnvironment.kt:427)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.createCoreEnvironment(K2JVMCompiler.kt:219)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:150)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:51)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:85)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:43)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:105)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1479)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:688)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.lang.AbstractMethodError: Receiver class dev.afanasev.sekret.kotlin.SekretComponentRegistrar does not define or inherit an implementation of the resolved method abstract registerProjectComponents(Lcom/intellij/mock/MockProject;Lorg/jetbrains/kotlin/config/CompilerConfiguration;)V of interface org.jetbrains.kotlin.compiler.plugin.ComponentRegistrar.
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.registerExtensionsFromPlugins$cli(KotlinCoreEnvironment.kt:569)
	... 28 more
```
This the stacktrace from IntelliJ.
The Kotlin plugin verison is: 1.3.72-release-IJ2020.1-5

**Comment by aafanasev** [comment]
Seems this request is not trivial as I thought because we need to check the value in runtime and then only replace an annotated property with `mask` or `null`. 

Thinking about a helper method which can be called from toString() if a property is annotated:
```kotlin
private fun getToStringValue(value: Any?, mask: String) : String? {
  return if (value == null) {
    null
  } else {
    mask
  }
}
```

@Vacxe any thoughts?

**Comment by aafanasev** [comment]
@mkopylec try out 0.0.6 version

**Comment by mkopylec** [comment]
It works, thanks
